#!/bin/bash
# Ayuda rápida para el proyecto VeriFactu

echo "🚀 AYUDA RÁPIDA - PROYECTO VERIFACTU"
echo "=================================="
echo ""
echo "📁 Ubicación actual: $(pwd)"
echo ""
echo "🔧 COMANDOS ÚTILES:"
echo ""
echo "   📊 Tests de verificación:"
echo "      php tests/test_instalacion.php"
echo ""
echo "   🔧 Configuración:"
echo "      ./quick_setup.sh               # Configuración interactiva"
echo "      nano .env                      # Editar configuración manual"
echo ""
echo "   🔧 Mantenimiento:"
echo "      composer install               # Reinstalar dependencias"
echo "      composer update                # Actualizar dependencias"
echo "      rm logs/*.log                  # Limpiar logs"
echo ""
echo "📋 ARCHIVOS IMPORTANTES:"
echo "   .env                            # Configuración (EDITAR)"
echo "   certificates/                   # Certificados (OBTENER FNMT)"
echo "   logs/                           # Logs del sistema"
echo ""
echo "🆘 PROBLEMAS FRECUENTES:"
echo ""
echo "   ❌ Necesito certificado FNMT:"
echo "      → https://www.sede.fnmt.gob.es/certificados/persona-fisica"
echo ""
echo "   ❌ 'Class not found':"
echo "      → Ejecutar: composer install"
echo ""
echo "📚 Más información: README.md"
echo ""
